---
- name: Install httpd and php
  ansible.builtin.yum:
    name:
      - httpd
      - php
      - php-mysqlnd
    state: present

- name: Install web role specific dependencies
  ansible.builtin.yum:
    name: git
    state: installed

- name: Start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: insert firewalld rule for httpd
  ansible.posix.firewalld:
    port: "{{ httpd_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true

- name: Allow Apache to connect to MySQL
  ansible.posix.seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: true

- name: Set index.php as the default page
  tags: Set index.php as the default page
  ansible.builtin.replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: DirectoryIndex index.html
    replace: DirectoryIndex index.php

- name: http service state
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: Copy the code from repository
  ansible.builtin.git:
    repo: "{{ repository }}"
    dest: /var/www/html
    force: true

- name: Creates the index.php file
  ansible.builtin.template:
    src: index.php.j2
    dest: /var/www/html/index.php
