---
- name: Deploy lamp stack application
  hosts: all
  become: true
  tasks:
    - name: Install common dependencies
      yum:
        name:
          - python3-libselinux
          - python3-libsemanage
          - firewalld
        state: installed

# Install and Configure Database
- name: Deploy lamp stack application
  hosts: lamp-db
  become: true
  tasks:
    - name: Install MariaDB package
      yum:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: installed

    - name: Create Mysql configuration file
      copy: src=files/my.cnf dest=/etc/my.cnf

    - name: Start MariaDB Service
      service: name=mariadb state=started enabled=yes

    - name: Start firewalld
      service: name=firewalld state=started enabled=yes

    - name: Insert firewalld rule
      firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=true