---
- name: Deploy lamp stack application
  hosts: all
  become: true
  tasks:
    - include_tasks: tasks/common.yml

# Install and Configure Database
- name: Deploy lamp stack application
  hosts: lamp-db
  become: true
  tasks:
    - include_tasks: tasks/db.yml

- name: Deploy lamp stack application
  hosts: lamp-web
  become: true
  tasks:
    - include_tasks: tasks/web.yml