---
- name: Deploy lamp stack application
  hosts: all
  become: true
  roles:
    - common

# Install and Configure Database
- name: Deploy lamp stack application
  hosts: lamp-db
  become: true
  roles:
    - mysql

- name: Deploy lamp stack application
  hosts: lamp-web
  become: true
  roles:
    - httpd-php
