---
- name: Install MariaDB package
  ansible.builtin.yum:
    name:
      - mariadb-server
      - python3-PyMySQL
    state: installed

- name: Create Mysql configuration file
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/my.cnf

- name: Start MariaDB Service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Insert firewalld rule
  ansible.posix.firewalld:
    port: "{{ mysql_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true

- name: Create Application Database
  community.mysql.mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: "{{ dbname }}"
    state: present

- name: Create Application DB User
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: "{{ dbuser }}"
    password: "{{ dbpassword }}"
    priv: "*.*:ALL"
    host: "{{ hostvars['lamp-web']['ansible_facts']['eth0']['ipv4']['address'] }}"
    state: present

- name: Move db-load-script to db host
  ansible.builtin.template:
    src: db-load-script.sql.j2
    dest: /tmp/db-load-script.sql

- name: Load Inventory Data
  ansible.builtin.shell: mysql -f < /tmp/db-load-script.sql
